name: Actions Workflows

on:
  push:
  pull_request:
   types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   steps:
    - name: List Files
      run: |
        pwd
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_REF
        echo $GITHUB_REPOSITORY
        echo $GITHUB_ACTOR
        echo $GITHUB_WORKFLOW
        echo $GITHUB_HEAD_REF
        echo $GITHUB_BASE_REF
        echo $GITHUB_EVENT_NAME
        echo $GITHUB_WORKSPACE
        echo $GITHUB_ACTION
        echo $"${{ github.token }}"
